### PR TITLE
 added new page with deployments

### PR DESCRIPTION
**Pull request by DmitryBespalov**
Added addresses of deployed safe contracts.

### CODE REVIEW

**Comment by rmeissner** [comment]
I requested to leave out all contracts prior to 1.0.0 (actually we should also remove 1.1.0 ... sorry) as these should not be used. Also 0.1.0 was only for the beta app.

If you really think we need them we can add 0.1.0 (but I would still remove 1.1.0).

I also think v1 and v2 for multisend are our "official" names (these are unrelated to the contract versions, e.g. 1.2.0 will not have another multisend).

SecureSafeFactory might make sense (https://github.com/gnosis/safe-factories)

**Comment by tschubotz** [comment]
> Edit: instead of adding all versions of the safe contracts we should probably link to the releases page of the safe-contracts repo (there users can look up the addresses ... somehow :P)

For 1.0.0 you would have to looks through the code at the time of the release since the addresses are not part of the release assets. https://github.com/gnosis/safe-contracts/releases
For 1.1.1 they are, however not super convenient.

> I also think v1 and v2 for multisend are our "official" names (these are unrelated to the contract versions, e.g. 1.2.0 will not have another multisend).

But a new Multisend will get deployed even though we are not using it, right? So it'll be part of hte networks.json, so wouldn't it make sense to mention it at least?
Also, if you are saying you would like to link to the github releases for addresses, there we don't call them v1 and v2. ;)

> I requested to leave out all contracts prior to 1.0.0 (actually we should also remove 1.1.0 ... sorry) as these should not be used. Also 0.1.0 was only for the beta app.

But this is for developer docs, so I thought it should contain as many details as possible. But ultimately your call what you want to see there.

**Comment by DmitryBespalov** [comment]
@tschubotz I like the doc you shared a lot - it has  much more information and with descriptions. I've put the safe-docs page first from the personal itch - to have the list somewhere, but the doc make sense. 

So. Do we need doc/PR?

**Comment by tschubotz** [comment]
Etherscan has since tagged the addresses accordingly: https://etherscan.io/accounts/label/gnosis-safe :)

I think we don't need this PR currently, otherwise we would have to maintain it also ;)

**Comment by DmitryBespalov** [comment]
Closing as it is not needed

**Pull request closed without merging**
