### PR TITLE
Add gasToken parameter + type refactoring

### PR DESCRIPTION
**Pull request by rmeissner**
- Update with type specifications from https://gitlab.gnosisdev.com/wallets/safe/merge_requests/37/diffs
- Specify that `gasToken` is never `null` in the estimate response
- Add `gasToken` to estimate request
  - https://github.com/gnosis/safe-relay-service/issues/18
  - https://github.com/gnosis/safe-relay-service/issues/19

### CODE REVIEW

**Comment by Uxio0** [comment]
GasToken to estimate request actually depends on gnosis/safe-relay-service#18. Everything is ok from my side, we will add the payment token to the creation endpoint when gnosis/safe-relay-service#19 is implemented

**Comment by rmeissner** [comment]
@Uxio0 I will wait with merging this until we have it in production ;)

**Comment by Uxio0** [comment]
Sounds good to me

**Comment by rmeissner** [comment]
@Uxio0 I also added the `paymentToken` to the response of the creation request

**Pull request merged**
